id: P7B654E34
initial_creation_type: input
source_metadata:
  Title: Vajras큰c카
  Editor: Dvivedi, Ramayana Prasad
  Publisher: Chaukhamba Amarbharati Prakasan
  Place of Publication: India
  Year: '1985'
  Vajras큰c카:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:51:27.479858'
last_modified_at: '2022-03-08T16:51:27.479868'
